### ISSUE TITLE
Doesn't render Linked files

### ISSUE THREAD

**Issue by Dracozny** [obsidian-community/obsidian-pandoc#6]
perhaps it's the unicode used..
```
![[🚩 - ✅ Yoshi]]
```
renders as [[🚩 - ✅ Yoshi]]

The standard Export to PDF doesn't have this issue. But it seems like all of the Pandoc plugins fail at this.  I was hoping to be able to export to Docx due to business needs.

**Comment by AB1908** [comment]
Hey there! I know there's been a bit of a mix up recently but can you post the issue to the original repo for now? OliverBalfour/obsidian-pandoc should be the one. Sorry for duplicating your efforts and also for the confusion.

**Comment by Dracozny** [comment]
Probably a dupe anyways. looking at the list (https://github.com/OliverBalfour/obsidian-pandoc/issues/80)
