### ISSUE TITLE
Update? And transcluding images?

### ISSUE THREAD

**Issue by ReaderGuy42** [obsidian-community/obsidian-pandoc#7]
Have there been any updates to this plugin? 

And I'm still having issues when I try to convert a file to OpenDocument (but probably also other formats) with images. I get the following error message, I assume it means that pandoc can't find the image?

![image](https://user-images.githubusercontent.com/71895400/194852178-7b7a48bf-f403-46f9-a7f9-47e9e3fc28a4.png)

Thanks!

**Comment by AB1908** [comment]
Hi ReaderGuy, Oliver has found some time again to update the plugin, can you open this issue there instead? We'll be shifting this into the archive for now.
